### ISSUE TITLE
"Welcome to Cloud Meter" screen

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/frontigrade#10]
As a cloudigrade user, I want to see a "Welcome to Cloud Meter" screen with an "Add Account" button when I log in if (and only if) I have no registered accounts so that I have a way to get started.

## Acceptance Criteria

- [x] Verify welcome screen appears if user has no registered account.
- [x] Verify welcome screen does not appear if user has any registered account.
  - ...because there will be a dashboard here instead!
- [x] Verify welcome screen looks like the design wireframes.
- [x] Verify "add account" button opens a modal box
  - The box may just have placeholder text and elements. Functional contents will come later!
- [x] Verify the modal has a "Cancel" button that closes it and returns the user to the "Welcome" screen.
- [x] Verify integration tests exist for at least "the happy paths".

## Assumptions and Questions

- Design is based on https://redhat.invisionapp.com/share/UFI078IZVAW
- This applies to all users. Not just regular users, but superusers also. **This is subject to change in the future** if we want to dissuade superusers from registering cloud accounts, perhaps not realizing what they're doing.

**Comment by elyezer** [comment]
Integration tests were added by https://github.com/cloudigrade/integrade/pull/31
