### ISSUE TITLE
"Add Account" modal part 1: Policy

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/frontigrade#11]
As a cloudigrade user, I want to see instructions for setting up my AWS Policy when I see the "Add Account" modal so that I know how to proceed with creating my AWS Policy.

## Acceptance Criteria

- [x] Verify the screen has visual elements and text that look like the design wireframes.
- [x] Verify there is a read-only text area containing the JSON definition for the AWS Policy.
- [x] Verify that clicking the "Copy" button copies the JSON definition to the clipboard.
- [x] Verify that clicking "Cancel" closes the modal and returns the user to the "Welcome" screen. 
- [x] Verify that clicking "Next" replaces the modal contents.
  - The replacement content may just be placeholder text. Functional contents will come later!
- [x] Verify that clicking "Back" from the _next_ placeholder view returns the user to this Policy screen.

## Assumptions and Questions

- Design is based on https://redhat.invisionapp.com/share/UFI078IZVAW
- ~Do we want the policy JSON to live as static content in frontigrade? Or should frontigrade ask the cloudigrade API for its current definition? The latter is more complex but means we don't have to update frontigrade if/when we change the policy requirements.~ A copy of the policy and all the relevant text live with frontigrade.
- In the future, we will have different text and layout when we expand support for Azure and GCP, and presumably we will have something at the start or before this step that indicates which cloud provider the user's account belongs to. We don't want to build explicit support for that now, but let's be mindful not to code ourselves into a bad place.

**Comment by cdcabrera** [comment]
Reference towards Patternfly styling regarding copy/paste ... https://github.com/patternfly/patternfly-ng/pull/351

**Comment by cdcabrera** [comment]
Demo as of 2018-06-22

![jun-22-2018 11-01-27](https://user-images.githubusercontent.com/3761375/41783778-be5114ac-760b-11e8-9065-69ef771bb399.gif)
