### ISSUE TITLE
"Add Account" modal part 2: Role

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/frontigrade#12]
As a cloudigrade user, I want to see instructions for setting up my AWS Role when I step through the "Add Account" modal so that I know how to proceed with creating my AWS Role.

## Acceptance Criteria

- [x] Verify that this new screen is show when the user clicks "Next" on the "Policy" step of the "Add Account" modal.
- [x] Verify the screen has visual elements and text that look like the design wireframes.
- [x] Verify there is a read-only text area containing cloudigrade's AWS Account ID.
- [x] Verify that clicking the "Copy" button copies cloudigrade's AWS Account ID to the clipboard.
- [x] Verify that clicking "Cancel" closes the modal and returns the user to the "Welcome" screen. 
- [x] Verify that clicking "Back" shows the previous "Policy" screen.
- [x] Verify that clicking "Next" replaces the modal contents.
  - The replacement content may just be placeholder text. Functional contents will come later!
- [x] Verify that clicking "Back" from the _next_ placeholder view returns the user to this Role screen.
- [x] Verify that a retrieve-only (`HTTP GET`) API exists at `/api/v1/sysconfig/` that includes the cloudigrade AWS Account Id that we want the customer to use when configuring her AWS Role.

## Assumptions and Questions

- Design is based on https://redhat.invisionapp.com/share/UFI078IZVAW
- ~Do we want the AWS Account ID to live as static content in frontigrade? Or should frontigrade ask the cloudigrade API for this value? The latter is more complex but means we don't have to update frontigrade if/when we change the AWS Account ID (which _will_ vary depending on environment).~
  - We discussed this question, and this value should come from the API somewhere.
    - `HTTP GET /api/v1/sysconfig/` should return an object like:
        ```
        {
            "aws_account_id": 1234567890
        }
        ```
    - TBD: How do we feel about that URL?
    - The object is very simple now, but it may grow to include more values (like an Azure account ID) in the future. Maybe in the future it'll look like:
        ```
        {
            "aws_account_id": 1234567890,
            "azure_account_id": 1234567890,
            "gcp_account_id": 1234567890
        }
        ```
    - TBD: Is there anything else clever we should put in this design to help future-proof ourselves?

**Comment by dsesami** [comment]
@cdcabrera I have a question about the wording in this role step -- 

> Create a new role in the AWS Identity and Access Management Steps when logging into AWS Identity and Access Management
> Paste this value into the Account ID field:
> 
When you go to the AWS Create Role page, it's not immediately obvious which type of Trusted Entity you need to paste the account ID value into. I'm assuming it's "Another AWS Account":

![screenshot from 2018-07-02 13-44-37](https://user-images.githubusercontent.com/19942822/42178362-1bcd9f8e-7dfe-11e8-8a61-1ce4a1076152.png)

If i'm right, could that be clarified in the instructions for ease of use?

**Comment by cdcabrera** [comment]
@dsesami clarification is always good! @cloudigrade/engineering @cloudigrade/ux-ui is there a recommendation for the correct `trusted entity` we should be placing in the steps?

**Comment by infinitewarp** [comment]
FWIW, the original instructions did not specify choosing "Another AWS Account" because they used to have a deep link into this page that automatically selected that type. Since we are no longer deep linking, I agree that we should clearly instruct the customer to select that type.

**Comment by dsesami** [comment]
@infinitewarp cool, thanks for the explanation.

**Comment by cdcabrera** [comment]
@dsesami @infinitewarp I'll go ahead and create a copy patch that incorporates the update

**Comment by infinitewarp** [comment]
I've checked all the boxes to verify all the AC _as written_, but I'll wait for @cdcabrera to smash in those wording changes before closing this off. 🙂
