### ISSUE TITLE
"Add Account" modal part 3: ARN

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/frontigrade#13]
As a cloudigrade user, I want to give cloudigrade my AWS Role's ARN so that cloudigrade can create my account.

Client-side format validation? Yes! TBD: Basic string pattern check.

TBD add another spike/user story/whatever to figure out a new type of error handler in DRF to pretty-up our error responses to have more details including an error code!

We need to define some kind of error API contract between the API and client so that the web client can present meaningful information to the end user. Important! For now, we will just deal with strings. The other story (TBD) will improve upon this with richer error code objects.

## Acceptance Criteria

- [x] Verify that this new screen is show when the user clicks "Next" on the "Role" step of the "Add Account" modal.
- [x] Verify the screen has visual elements and text that look like the design wireframes.
- [x] Verify there is an input text field for the user to enter an ARN.
- [x] Verify that clicking the "Copy" button copies cloudigrade's AWS Account ID to the clipboard.
- [x] Verify that clicking "Cancel" closes the modal and returns the user to the "Welcome" screen. 
- [x] Verify that clicking "Back" shows the previous "Role" screen.
- [x] Verify that clicking "Next" submits the user's ARN to cloudigrade for checking and saving.
- [x] Verify that when the user submits a malformed ARN, there is some helpful message on the screen indicating the problem. _Q: What does this look like?_ A: TBD!
- [x] Verify that when the user submits an ARN that does not have correct permissions set in its policy, there is some helpful message on the screen indicating the problem.  _Q: What does this look like?_  A: TBD!
- [x] Verify that when the user submits an ARN that is already known by cloudigrade for this user, there is some helpful message on the screen indicating the problem.  _Q: What does this look like?_ A: TBD!
- [x] Verify that the "Next" button is disabled until the user enters an ARN.
- [x] Verify that clicking "Next" replaces the modal contents.
  - The replacement content may just be placeholder text. Functional contents will come later!

## Assumptions and Questions

- Design is based on https://redhat.invisionapp.com/share/UFI078IZVAW
- Do we want to do "live" checking of the ARN as the user is entering before they press Next?
    - No. We only actually validate (in talking to AWS) when the user presses the go button.
- What is our error handling supposed to look like here?
    -  A: TBD!

**Comment by elyezer** [comment]
This issue get the cloud account creation wizard done. That said now we can automate the entire wizard flow and https://github.com/cloudigrade/integrade/issues/45 will take care of that.

**Comment by elyezer** [comment]
> Verify that when the user submits an ARN that does not have correct permissions set in its policy, there is some helpful message on the screen indicating the problem. Q: What does this look like? A: TBD!

I see that the UI is showing a message stating that there is no enough privileges. I wonder if it should show the list of missing permissions, what do you think?

> Verify that when the user submits an ARN that is already known by cloudigrade for this user, there is some helpful message on the screen indicating the problem. Q: What does this look like? A: TBD!

I was not able to verify this because the Cloudigrade started to give me 502 Bad Gateway errors

**Comment by ilyavw** [comment]
@elyezer seems a bit like scope creep. We shouldn't be teaching our customers to be adding permissions one at a time, ideally they copy the whole JSON object and paste that in, since every one of those permissions is required.

**Comment by ilyavw** [comment]
re: 502, is there a deployment happening?

**Comment by elyezer** [comment]
I was able to verify:

> Verify that when the user submits an ARN that is already known by cloudigrade for this user, there is some helpful message on the screen indicating the problem. Q: What does this look like? A: TBD!

![screenshot from 2018-07-09 10-44-08](https://user-images.githubusercontent.com/48132/42454163-269c7fae-8365-11e8-9f6d-373e78dda39d.png)

**Comment by elyezer** [comment]
@ilyavw re: 502, is there a deployment happening?

It seems to be the case, saw that we got some jobs running on travis. Now that there is no job running I was able to verify the last item.

**Comment by elyezer** [comment]
All AC items are now verified, time to close this issues.

**Comment by cdcabrera** [comment]
@elyezer @ilyavw we're good on frontigrade adding some type of additional 500 level error message display across the app in a follow up PR. 

@kdelee called this out too since an HTML body response can come across. Based purely on that HTML response we're thinking its a good path for a helpful display message instead

Catching up with @cloudigrade/ux-ui and we'll look at opening a separate issue.

**Comment by cdcabrera** [comment]
Annnd it looks @elyezer  opened an issue already... https://github.com/cloudigrade/frontigrade/issues/43 

Though not really sure that's bug so much as something that simply needed to be addressed, and that it affects everything from login to views, to components.
