### ISSUE TITLE
Add Account wizard gets broken whenever a 5XX error is faced

### ISSUE THREAD

**Issue by elyezer** [cloudigrade/frontigrade#43]
## Summary

The Add Account wizard gets broken whenever a 5XX error is faced during the creation of the cloud account.

The error page at the end of the wizard shows the following:

![screenshot from 2018-07-09 10-16-07](https://user-images.githubusercontent.com/48132/42453148-3ca763de-8362-11e8-90e7-841a3e2b7b71.png)

But navigating back the message is also shown on the fields validation message:

![screenshot from 2018-07-09 10-15-50](https://user-images.githubusercontent.com/48132/42453177-53196806-8362-11e8-9d40-fc18e3501d85.png)

![screenshot from 2018-07-09 10-15-35](https://user-images.githubusercontent.com/48132/42453183-570b7396-8362-11e8-85ae-1d470f75196f.png)

That also makes the field values to be considered invalid even though they are valid (which allowed the user to go all the way to the end of the wizard).

## Steps to Reproduce

1. Getting a 5XX error is not a trivial task (even though we are getting that more frequently than it should on OSD) but maybe this can be mocked by posting to https://httpbin.org/status/500 for example.

## Expected Result

- The wizard steps and validation fields are isolated from each other.
- Whenever a 5XX error is returned during the account creation or when doing a request to the API a consistent error UI should be shown. By consistent I mean having a dedicated UI for this because the 5XX errors can be faced when checking API for the AWS account id for example (not sure where that would be shown).

## Actual Result

- The wizard steps and validation are somewhat sharing some state which causes wrong behavior.
- The 5XX error is shown with escaped HTML tags and there is no consistent UI for displaying them.

**Comment by cdcabrera** [comment]
@cloudigrade/engineering @cloudigrade/ux-ui @cloudigrade/quality-engineering 

We can put 500 level checks in the Wizard steps to address the issue, it'll be a band-aid fix. We think this needs to be addressed in a `pilot` level story instead. 

500 level errors are going to affect everything from login, views to components. Right now we're just seeing the tip of the iceberg with the Wizard. The decision, "should a user be logged out in a graceful way" when a 500 is detected needs to be addressed.

**Comment by elyezer** [comment]
Do you mean login out from UI without touching the API? Because the 5XX may be affecting the login/logout API machinery.

Not sure if there is a common expected behavior for this but logging out seems reasonable to avoid the user seeing more 5XX or errors on the UI

**Comment by cdcabrera** [comment]
Going to approach this at 2 levels. First we'll put in a 500 level check at the component level, that should help close this issue. 

And second we'll put in a 500 level check at the application level, which should address the more global piece. Along the lines of a toast notification that addresses the `API is disconnected, trying to reconnect`. The case for this second approach so far, we think, should be limited or rare mostly popping up during development
